name: Publish

on:
  push:
    tags:
      - v*

jobs:
  github-release:
    runs-on: ubuntu-18.04
    name: Publish GitHub Release
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Install build dependencies
        run: pip install wheel
      - name: Build packages
        run: python setup.py sdist bdist_wheel
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pypi:
    runs-on: ubuntu-18.04
    name: Publish package on PyPI
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Install build dependencies
        run: pip install wheel
      - name: Build packages
        run: python setup.py sdist bdist_wheel
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
